### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by felixhayashi** [tobibeer/tb5#1] opened 2016-01-21 09:13 UTC
Hi @tobibeer 

the tw-search doesn't seem to work at tb5. Can you verify? It doesn't create a dropdown.

http://tobibeer.github.io/tb5/

**Comment by felixhayashi** [comment] 2016-01-21 09:21
Maybe it happened because of your latest popup hijacking experiments ;) If you need a quick fix: http://spangenhelm.github.io/TW5-EnhancedSearchResults/

**Comment by tobibeer** [comment] 2016-01-21 11:42
@felixhayashi, works fine for me in both chrome and firefox:

![search](https://cloud.githubusercontent.com/assets/97566/12479575/48d4de70-c03c-11e5-8a90-ba72820a70ef.jpg)

**Comment by tobibeer** [comment] 2016-01-21 11:48
@felixhayashi, but I'll go and test http://spangenhelm.github.io/TW5-EnhancedSearchResults anyway. :-)

**Comment by tobibeer** [comment] 2016-01-21 11:50
Ok, one thing I notice, oddly is that the core dropdown is **not** a sticky one, it doesn't have `tc-popup-keep`. I guess that was an oversight by Jeremy.

**Comment by felixhayashi** [comment] 2016-01-21 12:03
Hi @tobibeer strange,

I tested it with Chrome 47 and FF 43 on linux and in both cases the search popup doesn't open. Did refresh etc. What I noticed is when I click outside somewhere and back inside the search box it opens for a millisecond and disappears again. Works fine on tiddlywiki.com though and on some other 5.10.0 wikis I tested…

![2016-01-21 13 00 39](https://cloud.githubusercontent.com/assets/4307137/12479963/090890d6-c03f-11e5-82b8-e9ba50983a68.png)

**Comment by felixhayashi** [comment] 2016-01-21 12:06
> @felixhayashi, but I'll go and test http://spangenhelm.github.io/TW5-EnhancedSearchResults anyway. :-)

:+1:

**Comment by tobibeer** [comment] 2016-01-21 14:22
@felixhayashi, mhhh, I get the feeling that I misunderstood and thus ignored the meaning of `tc-popup-handle` in my popup modifications.

@jermolene: It appears to produce the same effect as `tc-popup-keep`?!?

**Comment by tobibeer** [comment] 2016-01-22 16:07
Ok, the problem is in how TiddlyWiki has these different "popups" that sometimes are called "dropdowns". Well, turns out that those "dropdowns" are getting their zIndex via css and not via `positoinPopup()` ...and so stuff breaks with my code.

I never really got why there would ever be a distinction ...and why some "popups" get to be called "dropdowns" ...and even are handled differently. Makes things soooo much harder, not only to debug. If it was for styling, ok... let them have a tc-dropdown class. Other than that, please use the same codebase!

**Comment by tobibeer** [comment] 2016-01-22 16:18
Sorry, a bit frustrated right now, because all the popup stuff is opaque enough as is... and now that "dropdowns" are increasing the mess isn't helping a lot.

**Comment by tobibeer** [comment] 2016-01-22 21:27
fixed with https://github.com/tobibeer/tw5-appear/releases/tag/0.6.1

**Closed by tobibeer** 2016-01-22 21:27 UTC

**Comment by felixhayashi** [comment] 2016-01-23 09:44
Many thanks @tobibeer. Interference issues are very difficult to spot… glad you solved it :+1:
